[package]
name = "frameassembly"
version = "0.6.0"
edition = "2024"
description = "A Domain-Specific Language (DSL) for writing deterministic network traffic to .pcap files."
authors = ["Steve Winschel"]
license = "MIT"

[dependencies]

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
