[package]
name = "frameassembly"
version = "0.9.1"
edition = "2024"
description = "A Domain-Specific Language (DSL) for writing deterministic network traffic to .pcap files."
authors = ["Steve Winschel"]
license = "MIT"
repository = "https://github.com/stevewinschel/frameassembly"
keywords = ["pcap", "networking", "dsl", "packet-crafting", "security"]
categories = ["network-programming", "development-tools::testing"]

[dependencies]
etherparse = "0.21.0"
logos = "0.14.3"
miette = { version = "7.6.0", features = ["fancy"] }
pcap-file = "2.0.0"
rasn = "0.28.15"
rasn-smi = "0.28.15"
rasn-snmp = "0.28.15"
winnow = "1.0.4"

[profile.dev]
opt-level = 0
codegen-units = 256
debug = true
panic = "abort"

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
panic = "abort"